.. |pd| replace:: PyDealer
.. |fd| replace:: French Deck

.. |_pd| replace:: `PyDealer <https://github.com/trebek/pydealer>`__
.. |_fd| replace:: `French deck <https://en.wikipedia.org/wiki/Standard_52-card_deck>`__

.. |card| replace:: :class:`~pydealer.card.Card`
.. |stack| replace:: :class:`~pydealer.stack.Stack`
.. |deck| replace:: :class:`~pydealer.deck.Deck`
.. |modcard| replace:: :mod:`~pydealer.card`
.. |modstack| replace:: :mod:`~pydealer.stack`
.. |moddeck| replace:: :mod:`~pydealer.deck`
.. |modutils| replace:: :mod:`~pydealer.utils`
.. |modconst| replace:: :mod:`~pydealer.const`

.. _pip: https://pypi.python.org/pypi/pip/
.. _Python Package Index: https://pypi.python.org/pypi/pydealer/
.. _French deck: https://en.wikipedia.org/wiki/Standard_52-card_deck

.. |check| unicode:: 0x2713
    :trim:
.. |ballotx| unicode:: 0x2717
    :trim:

.. |spade| unicode:: 0x2660
    :trim:
.. |club| unicode:: 0x2663
    :trim:
.. |heart| unicode:: 0x2665
    :trim:
.. |diamond| unicode:: 0x2666
    :trim: